name: revista_tr_cuadros
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas==2.1.4
    - jupyterlab
    - python-dotenv
    - PyYAML
    - openpyxl
    # WEB UI DEPENDENCIES
    - Flask==3.0.0
    - Flask-WTF==1.2.1
    - WTForms==3.1.0
    - Werkzeug==3.0.1
